macro(SimpleGTKConfig)
if(NOT WIN32 AND NOT APPLE AND NOT QT_ANDROID)
    find_package(GTK2)

    if(GTK2_FOUND AND NOT "$ENV{BUILD_GTK3}" STREQUAL "TRUE")
        set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --toolkit=gtk2)
        include_directories(${GTK2_INCLUDE_DIRS})
        set(GTK_LIBRARIES ${GTK2_LIBRARIES})
        message(STATUS "${CMLOC}Building against GTK2...")
    else(GTK2_FOUND AND NOT "$ENV{BUILD_GTK3}" STREQUAL "TRUE")
        find_package(GTK3)
        if(GTK3_FOUND)
            include_directories(${GTK3_INCLUDE_DIRS})
            set(GTK_LIBRARIES ${GTK3_LIBRARIES})
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__WXGTK3__")
            set(wxWidgets_CONFIG_OPTIONS ${wxWidgets_CONFIG_OPTIONS} --toolkit=gtk3)
            message(STATUS "${CMLOC}Building against GTK3...")
        else(GTK3_FOUND)
            message(STATUS "${CMLOC} Unix: Neither FATAL_ERROR GTK2 nor GTK3")
        endif(GTK3_FOUND)
    endif(GTK2_FOUND AND NOT "$ENV{BUILD_GTK3}" STREQUAL "TRUE")
    set(EXTRA_LIBS ${EXTRA_LIBS} ${GTK_LIBRARIES})
endif(NOT WIN32 AND NOT APPLE AND NOT QT_ANDROID)
endmacro(SimpleGTKConfig)
